version: '2'
services:
  postgres:
    image: postgres:9.5
    restart: always
    container_name: yii2_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db_yii2'
    volumes:
      - "./docker/data/postgresql:/var/lib/postgresql/data/:cached"
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 8080:8080
  php:
    image: yiisoftware/yii2-php:7.2-apache
#    image: yiisoftware/yii2-php:7.2-fpm
    container_name: yii2_php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
# psql "postgresql://root:password@postgres/db_yii2"